spring:
  application:
    name: stock-price
server:
  port: 9090
  servlet:
     context-path: /market
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value} 